### ISSUE TITLE
KEYWORDS="**" is invalid

### ISSUE THREAD

**Issue by l29ah** [salfter/portage#3]

**Comment by salfter** [comment]
Please elaborate.  I'm fairly sure I saw it used somewhere else in ebuilds that shouldn't be keyworded as anything in particular.  What would you suggest as a replacement?

**Comment by l29ah** [comment]
I don't know what do you mean by "**", and https://dev.gentoo.org/~ulm/pms/head/pms.html#x1-270003.1.6 doesn't specify "**" as a valid keyword.

**Comment by l29ah** [comment]
Paludis reacts with this:
```
Error:
  * In program /usr/bin/cave -c y show app-crypt/vanitygen:
  * When finding all versions grouped by slot from packages matching app-crypt/vanitygen with filter all matches:
  * When generating metadata for ID 'app-crypt/vanitygen-9999::salfter':
  * When loading generated metadata for 'app-crypt/vanitygen-9999::salfter':
  * Name '**' is not a valid keyword name (paludis::KeywordNameError)
```

**Comment by salfter** [comment]
Never heard of Paludis; emerge never complained.  Upon taking a look at https://devmanual.gentoo.org/keywording/, though, I've changed keywords on the affected ebuilds to ~amd64 (as that's mostly what I'm running). It's in commit 2fc5591.
